---
- name: Block And All playbook example
  hosts: local
  become: yes
  tasks:
    - name: Always Do X
      block:
        - name: Print a message
          debug:
            msg: 'I execute normally'

        - name: Force a failure
          command: /bin/false

        - name: Never print this
          debug:
            msg: 'I never execute'
      rescue:
        - name: Print when errors
          debug:
            msg: 'I caught an error, can do stuff here to fix it, :-)'

        - name: Force a failure in middle of recovery! >:-)
          command: /bin/false

        - name: Never print this
          debug:
            msg: 'I also never execute :-('
      always:
        - name: Always Do this
          debug:
            msg: "This always executes, :-)"
