---
- name: Block With Handlers playbook example
  hosts: local
  become: yes
  tasks:
    - name: Attempt and graceful roll back demo
      block:
        - name: Print a message
          debug:
            msg: 'I execute normally'
          changed_when: yes
          notify: run me even after an error

        - name: Force a failure
          command: /bin/false

      rescue:
        - name: Make sure all handlers run
          meta: flush_handlers

  handlers:
        - name: Run me even after an error
          debug:
            msg: 'This handler runs even on error'