---
- name: Example for delegate to
  hosts: centosserver
  become: yes
  tasks:
    # - name: print httpd version
    #   command: /usr/sbin/httpd -v
    #   delegate_to: localhost
    - name: install apache2
      apt:
        name: apache2
        state: present
        delegate_to: 172.31.38.65
        # allow_downgrade : yes
        # download_only: yes
        # delegate_to: web.jboss.etm1
        # when: "ansible_fact['distribution']== 'CentOS'"