---
- name: Example for delegate to
  hosts: webserver
  become: yes
  tasks:
    - name: print httpd version
      command: /usr/sbin/httpd -v
    - name: install httpd
      yum:
        name: httpd
        state: latest
        allow_downgrade : yes
        delegate_to: web.jboss.etm1
        when: "ansible_fact['distribution']== 'CentOS'"