---
- name: Dictionary playbook example
  hosts: webserver
  vars: 
    - mydict: {
               'Name': 'Shub', 
               'Email': 'sk.middlewareinventory.com', 
               'location': 'chennai'
               }

  tasks:
    - name: Display the Dictionary
      set_fact:
        mydict2: "{{ mydict2 | default({ 'Name': 'Sarav'})}}"
        mydict: "{{ mydict | default({})}}"
    - name: Display the Dictionaries
      debug: var="{{item}}"
      loop:
        - 'mydict2'
        - 'mydict'