---
- name: Dictionary playbook example
  hosts: webserver
  become: yes
  tasks:
    - include_vars: dict.yml

    - name: Display the data type of data
      debug:
        msg: "x: {{x | type_debug}} / y: {{y |type_debug}}"
    - debug:
        msg: "{{x['b1'] | type_debug}}"
    - debug:
      var: x['b1']
    - debug:
        msg: "{{y[0] | type_debug}}"
    - debug:
        var: y[0]
