---
- name: Dictionary playbook example
  hosts: webserver
  tasks:
    - name: Display the Dictionary
      set_fact:
        mydict2: "{{ mydict2 | default({ 'Name': 'Sarav'})}}"
        mydict: "{{ mydict | default({})}}"
    - name: Display the Dictionaries
      debug: var="{{item}}"
      loop:
        - 'mydict2'
        - 'mydict'
    
    - name: Create and Add items to dictionary
      set_fact: 
          userdata: "{{ userdata | default({}) | combine ({ item.key : item.value }) }}"
      with_items:
        - { 'key': 'Name' , 'value': 'SaravAK'}
        - { 'key': 'Email' , 'value': 'sarav@gritfy.com'}
        - { 'key': 'Location' , 'value': 'Coimbatore'}
        - { 'key': 'Nationality' , 'value': 'Indian'}

    -  name: Display the Dictionary
       debug: var=userdata