---
- name: Dictionary playbook example
  hosts: webserver
  tasks:
    - name: Create and Add items to dictionary
      set_fact: 
          userdata: "{{ tags | dict2items }}"
      tags:
      - key: Application
        value: payment
      - key: Environment
        value: dev
    -  name: Display the Dictionary
       debug: var=userdata