---
- name: concatenate list elements of dictionary
  hosts: webserver
  vars:
    users:
      - username: alice
        email: alice@example.com
      - username: bob
        email: bob@example.com
    #List
    hello: [Asia, Americas, Artic, Antartic ,Oceania,Europe,Africa]
    #Dict
    python:
      Designer: 'Guido van Rosum'
      Developer: 'Python Software Foundation'
      OS: 'Cross-platform'

  tasks:
    - name: concatanate list of elements
      debug:
        msg: "{{ users | map('json_query','email') | list | join('; ') }}"
      delegate_to: localhost
    
    - name: Ansible array(List) variables example
      debug: 
        msg: "{{ item }}"
      with_items:
        - "{{ hello }}"
    - name: Ansible Dictionary Example
      debug:
        msg: "{{ python }}"
    - name: Ansible Hash Example
      debug:
        msg: "{{python['Designer'] }}"
    - name: Ansible Find Example
      debug:
        msg: "{{python.Developer }}"