---
- name: Dictionary playbook example
  hosts: local
  become: yes
  vars:
    names: ["Miles","Sonny","Red","Paul","Philly"]
    instruments: ["Trumpet","Saxophone","Piano","Bass","Drums"]
  tasks: 
    - name: Get dict from list
      set_fact:
        band: "{{ band | default([]) + [ { 'names': item.0, 'instruments': item.1 } ]}}"
      with_together:
        - "{{ names }}"
        - "{{ instruments }}"
    
    - name: Get dict from list output
      debug: var=band