---
- name: concatenate list elements of dictionary
  hosts: webserver
  vars:
    users:
      - username: alice
        email: alice@example.com
      - username: bob
        email: bob@example.com

  tasks:
    - name: concatanate list of elements
      debug:
        msg: "{{ users | map('json_query','email') | list | join('; ') }}"
      delegate_to: localhost