---
- name: Example for delegate to
  hosts: centosserver
  become: yes
  vars:
    foo: "Line one \nLine two \nLine Three"
    version: 'Version: 6.8.2.14'
  tasks:
   - name: display the content for "foo" variables
     debug:
        var: foo
   - name: display the content for "foo" variables with filter
     debug:
        msg: "{{ foo | regex_search('.two.*',ignorecase=true) }}"
   - name: display the content for "foo" variables with filter one
     debug:
        msg: "{{ foo | regex_search('.*Line.*') }}"
   - name: display the content for "foo" variables with filter multiline
     debug:
        msg: "{{ foo | regex_search('.*Line.*', multiline=True, ignorecase=True) }}"
   - name: Debug version
     debug:
        msg: "{{ version | regex_search('.Version:[0-9]*') }}"
        # vars:
        # version_re: '^Version:\s+(\d+\.\d+.\d+\.\d+)'