---
- name: Example for delegate to
  hosts: centosserver
  become: yes
  vars:
    foo: "Line one \nLine two \nLine Three"
  tasks:
   - name: display the content for "foo" variables
     debug:
        var: foo