---
- name: Example for Register feature
  hosts: webserver
  become: yes
  tasks:
    - name: create one txt file
      file:
        name: var/tmp/sk.txt
        state: touch
    - name: finding all text file in /tmp folder
      shell: "find */tmp/* -name *.txt"
      register: myoutput
    - name: read the output
      debug:
        var: myoutput.stdout_lines
        # var: myoutput