---
- name: setting facts
  hosts: webserver
  become: yes
  tasks:
    - name: Setting host facts using key=value pairs, this format can only create strings or booleans
      set_fact: one_fact="something" other_fact="{{ local_var }}"

    - name: Setting facts so that they will be persisted in the fact cache
      set_fact:
        one_fact: something
        other_fact: "{{ local_var * 2 }}"
        cacheable: yes

    - name: Creating list and dictionary variables
      set_fact:
        one_dict:
            something: here
            other: there
        one_list:
            - a
            - b
            - c

    - name: Creating list and dictionary variables using 'shorthand' YAML
      set_fact:
        two_dict: {'something': here2, 'other': somewhere}
        two_list: [1,2,3]