---
- name: debugger playbook
  hosts: webserver
  become: yes
  tasks:
    - name: debug msg 
      debug:
        msg: "debug"
    - name: wrong variable
      file:
        path: "{{ file_path }}"
        state: touch
    - name: debug msg jst for checking
      debug:
        msg: "hi this is debug"